/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutStrongholdImport } from './routes/_layout/stronghold'
import { Route as LayoutJwtImport } from './routes/_layout/jwt'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutStrongholdRoute = LayoutStrongholdImport.update({
  id: '/stronghold',
  path: '/stronghold',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutJwtRoute = LayoutJwtImport.update({
  id: '/jwt',
  path: '/jwt',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/jwt': {
      id: '/_layout/jwt'
      path: '/jwt'
      fullPath: '/jwt'
      preLoaderRoute: typeof LayoutJwtImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/stronghold': {
      id: '/_layout/stronghold'
      path: '/stronghold'
      fullPath: '/stronghold'
      preLoaderRoute: typeof LayoutStrongholdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutJwtRoute: typeof LayoutJwtRoute
  LayoutStrongholdRoute: typeof LayoutStrongholdRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutJwtRoute: LayoutJwtRoute,
  LayoutStrongholdRoute: LayoutStrongholdRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/jwt': typeof LayoutJwtRoute
  '/stronghold': typeof LayoutStrongholdRoute
  '/': typeof LayoutIndexRoute
}

export interface FileRoutesByTo {
  '/jwt': typeof LayoutJwtRoute
  '/stronghold': typeof LayoutStrongholdRoute
  '/': typeof LayoutIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/jwt': typeof LayoutJwtRoute
  '/_layout/stronghold': typeof LayoutStrongholdRoute
  '/_layout/': typeof LayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/jwt' | '/stronghold' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/jwt' | '/stronghold' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/jwt'
    | '/_layout/stronghold'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/jwt",
        "/_layout/stronghold",
        "/_layout/"
      ]
    },
    "/_layout/jwt": {
      "filePath": "_layout/jwt.tsx",
      "parent": "/_layout"
    },
    "/_layout/stronghold": {
      "filePath": "_layout/stronghold.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
